# Site settings
title: "Taejeong Yoo Portfolio"
description: "A portfolio template for Taejeong's Work Experience."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Taejeong Yoo"
resume_title:                   "TSD of Gownet"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dbxowjd1396@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+82)10-4679-1396"
resume_contact_address:         "dbxowjd1396@gmail.com"

resume_header_contact_info:     "#512 	12, Jong-ro 35-gil, Jongno-gu, Seoul • (+82)10-4679-1396 • dbxowjd1396@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hello, I’m Taejeong Yoo. I graduated from Dongseo University with a major in Applied AI Engineering, formerly known as Information and Communication Engineering. Through various internal and external activities, I honed my leadership skills and learned the importance of collaboration, enabling me to cultivate the power of teamwork.💻</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://yootaejeong.github.io"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:            "https://statuesque-humerus-bb5.notion.site/_-aab12c4f7c1b476aa875874598fe1bc8?pvs=74"
  resume_linkedin_url:          "https://www.linkedin.com/in/taejeong-yoo-0706602a6/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           ""
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
